"""add shipment event

Revision ID: 51634ebc07a4
Revises: 70a6fd09b933
Create Date: 2026-06-16 12:22:55.102337

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "51634ebc07a4"
down_revision: Union[str, Sequence[str], None] = "70a6fd09b933"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shipment_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("location", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(name="shipmentstatus", create_type=False),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "seller",
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("seller", sa.Column("zip_code", sa.Integer(), nullable=True))
    op.drop_column("shipment", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shipment",
        sa.Column("status", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    )
    op.drop_column("seller", "zip_code")
    op.drop_column("seller", "address")
    op.drop_table("shipment_event")
    # ### end Alembic commands ###
