"""adding delivery partner table

Revision ID: 70a6fd09b933
Revises:
Create Date: 2026-06-15 14:59:03.676904

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "70a6fd09b933"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # use a non-native enum for the status column to avoid CREATE TYPE
    shipmentstatus = sa.Enum(
        "placed",
        "in_transit",
        "out_for_delivery",
        "delivered",
        name="shipmentstatus",
        native_enum=False,
    )

    op.create_table(
        "delivery_partner",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("serviceable_zip_codes", sa.ARRAY(sa.INTEGER()), nullable=True),
        sa.Column("max_handling_capacity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "seller",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shipment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("destination", sa.Integer(), nullable=False),
        sa.Column("status", shipmentstatus, nullable=False),
        sa.Column("estimated_delivery", sa.DateTime(), nullable=False),
        sa.Column("seller_id", sa.Uuid(), nullable=False),
        sa.Column("delivery_partner_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["delivery_partner_id"],
            ["delivery_partner.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["seller.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shipment")
    op.drop_table("seller")
    op.drop_table("delivery_partner")
    # ### end Alembic commands ###
