"""adds tag table

Revision ID: 85d948fd98e2
Revises: 626c6830fc11
Create Date: 2026-06-22 12:50:06.369867

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "85d948fd98e2"
down_revision: Union[str, Sequence[str], None] = "626c6830fc11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "name",
            sa.Enum(
                "Express",
                "STANDARD",
                "FRAGILE",
                "HEAVY",
                "INTERNATIONAL",
                "DOMESTIC",
                "TEMPERATURE_CONTROLLED",
                "GIFT",
                "RETURN",
                "DOCUMENTS",
                name="tagname",
            ),
            nullable=False,
        ),
        sa.Column("instructions", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shipment_tag",
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("shipment_id", "tag_id"),
    )
    # ### end Alembic commands ###

    ### Add tag entries in the database
    op.execute(
        sa.text(
            """
            INSERT INTO tag (id, name, instructions)
            VALUES
                (gen_random_uuid(), 'Express', 'Prioritize this shipment for expedited handling and fastest available routing.'),
                (gen_random_uuid(), 'STANDARD', 'Process this shipment through the standard delivery workflow.'),
                (gen_random_uuid(), 'FRAGILE', 'Handle this shipment carefully and avoid stacking heavy items on top.'),
                (gen_random_uuid(), 'HEAVY', 'Use appropriate lifting support and verify weight limits during handling.'),
                (gen_random_uuid(), 'INTERNATIONAL', 'Confirm customs documentation and route through international processing.'),
                (gen_random_uuid(), 'DOMESTIC', 'Route this shipment through domestic carrier services only.'),
                (gen_random_uuid(), 'TEMPERATURE_CONTROLLED', 'Maintain the required temperature range throughout storage and transit.'),
                (gen_random_uuid(), 'GIFT', 'Preserve gift packaging and avoid exposing pricing details to the recipient.'),
                (gen_random_uuid(), 'RETURN', 'Route this shipment through the returns intake and inspection workflow.'),
                (gen_random_uuid(), 'DOCUMENTS', 'Keep documents flat, dry, and protected from bending during transit.')
            """
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shipment_tag")
    op.drop_table("tag")
    # ### end Alembic commands ###
