"""adds servicable

Revision ID: ae4d518503d6
Revises: 85d948fd98e2
Create Date: 2026-06-24 14:53:01.015649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae4d518503d6'
down_revision: Union[str, Sequence[str], None] = '85d948fd98e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('zip_code')
    )
    op.create_table('Servicable_location',
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.zip_code'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['delivery_partner.id'], ),
    sa.PrimaryKeyConstraint('partner_id', 'location_id')
    )
    op.drop_column('delivery_partner', 'serviceable_zip_codes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner', sa.Column('serviceable_zip_codes', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_table('Servicable_location')
    op.drop_table('location')
    # ### end Alembic commands ###
